# Generated by Django 2.2.5 on 2019-09-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='issue_a',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='issue_b',
            field=models.CharField(max_length=30),
        ),
    ]
